name: Docker Image CI

env:
  DEFAULT_TAG: ${{ github.run_id }}-${{ github.run_attempt }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker Image
      run: docker build -t docker-kii-project . --tag igorceee/docker-kii-project:$DEFAULT_TAG

    - name: Docker Push
      run: docker push igorceee/docker-kii-project:$DEFAULT_TAG
      
    - name: Build the Docker Image Latest
      run: docker build -t docker-kii-project . --tag igorceee/docker-kii-project:latest

    - name: Docker Push Latest
      run: docker push igorceee/docker-kii-project:latest
      
    - name: Build the stack
      run: docker-compose up -d
